application: your-app-id
version: master
runtime: python27
api_version: 1
threadsafe: true

includes:
  - tailbone/admin
  - tailbone/files
  - tailbone/events
  - tailbone/js
  - tailbone/search
  # - tailbone/proxy
  # restful must come last in the includes because it matches /api/*
  - tailbone/restful

env_variables:
  NAMESPACE: '' # The datastore namespace '' for default

handlers:
  # # Add your own custom apps and handlers if you want to extend this
  # - url: /custom/.*
  #   script: custom.app

  # This links everything else in your client/app folder to be served
  # Change this to something else if your public folder is not client/app
  - url: (/?.*)/
    static_files: client/app\1/index.html
    upload: client/app(.*)/index.html
  - url: /
    static_dir: client/app

builtins:
  - appstats: on
  - deferred: on
  - admin_redirect: on
  - remote_api: on

inbound_services:
  - warmup
  - channel_presence

admin_console:
  pages:
  - name: Datastore Abuse
    url: /api/admin/abuse

pagespeed:
  # domains_to_rewrite:
  # - somedomainslowdomain.com
  # url_blacklist:
  # - http://myapp.com/dontoptomize/*
  enabled_rewriters:
  - MinifyCss
  disabled_rewriters:
  - LazyloadImages
  # Available rewriters
  # - ProxyCss # - default
  # - ProxyImages # - default
  # - ProxyJs # - default
  # - ConvertMetaTags # - default
  # - InlineCss # - default
  # - InlineJs
  # - InlineImages
  # - InlinePreviewImages # - default
  # - CollapseWhitespace
  # - CombineHeads
  # - ElideAttributes
  # - RemoveComments
  # - RemoveQuotes
  # - LeftTrimUrls

  # - CombineCss # - default
  # - MoveCssToHead # - default
  # - MinifyCss

  # - WebpOptimization # - default
  # - ImageConvertToJpeg # - default
  # - ImageRecompressJpeg # - default
  # - ImageProgressiveJpeg # - default
  # - ImageRecompressPng # - default
  # - ImageStripMetadata # - default
  # - ImageStripColorProfile # - default
  # - ImageResize # - default
  # - LazyloadImages # - default
  # - ImageAddDimensions

  # - CombineJs # - default
  # - JsOptimize # - default
  # - DeferJs

