application: your-app-id
version: master
runtime: python27
api_version: 1
threadsafe: true

includes:
  ## Base includes such as a combined /tailbone.js from included modules to follow
  - tailbone
  ## Qunit tests (only works when running locally)
  - tailbone/test
  ## Basic App Engine authentication
  # - tailbone/auth_gae
  ## Extra admin commands and interfaces (not done yet)
  # - tailbone/admin
  ## Upload files to blobstore (TODO: also allow cloud storage)
  # - tailbone/files
  ## Listen to and bind to global events with javascript and the channel api
  - tailbone/events
  ## Send direct messages between clients with the channel api
  - tailbone/messages
  ## Add the users location in headers via geoip lookup
  # - tailbone/geoip
  ## Full text search must provide a searchable.json at the root level
  # - tailbone/search
  ## Simple reverse proxy sometimes useful for cors purposes (note: don't use if you don't have to it
  ## will cost you bandwidth and has no auth)
  # - tailbone/proxy
  ## Clocksync simple synchronization of clocks
  - tailbone/clocksync
  ## Websocket+WebRTC based mesh server with rooms and load balancing
  - tailbone/compute_engine/mesh
  ## Order in this list is important for restful and pathrewrite, they must be last.
  ## Restful resources
  - tailbone/restful
  ## Any path without a file extension not in /api gets the app/client/index.html text. Useful for
  ## html5 applications that use the history api to write their paths.
  # - tailbone/pathrewrite

env_variables:
  JSONP: 'false' # Set to true to enable jsonp
  METADATA: 'false' # use a sharded counter to store totals for counts of types of models, fetch with HEAD

handlers:
  # # Add your own custom apps and handlers if you want to extend this
  # - url: /custom/.*
  #   script: custom.app

  # This links everything else in your client/app folder to be served
  # Change this to something else if your public folder is not client/app
  - url: (/?.*)/
    static_files: client/app\1/index.html
    upload: client/app(.*)/index.html
  - url: /
    static_dir: client/app

builtins:
  - appstats: on
  - deferred: on
  - admin_redirect: on
  - remote_api: on

inbound_services:
  - warmup
  - channel_presence

skip_files:
  - ^(.*/)?index\.yaml
  - ^(.*/)?index\.yml
  - ^(.*/)?#.*#
  - ^(.*/)?.*~
  - ^(.*/)?.*\.py[co]
  - ^(.*/)?.*/RCS/.*
  - ^(.*/)?\..*

pagespeed:
  # domains_to_rewrite:
  # - slowdomain.com
  # url_blacklist:
  # - http://myapp.com/dontoptomize/*
  enabled_rewriters:
  - MinifyCss
  disabled_rewriters:
  - LazyloadImages
  # Available rewriters
  # - ProxyCss # - default
  # - ProxyImages # - default
  # - ProxyJs # - default
  # - ConvertMetaTags # - default
  # - InlineCss # - default
  # - InlineJs
  # - InlineImages
  # - InlinePreviewImages # - default
  # - CollapseWhitespace
  # - CombineHeads
  # - ElideAttributes
  # - RemoveComments
  # - RemoveQuotes
  # - LeftTrimUrls

  # - CombineCss # - default
  # - MoveCssToHead # - default
  # - MinifyCss

  # - WebpOptimization # - default
  # - ImageConvertToJpeg # - default
  # - ImageRecompressJpeg # - default
  # - ImageProgressiveJpeg # - default
  # - ImageRecompressPng # - default
  # - ImageStripMetadata # - default
  # - ImageStripColorProfile # - default
  # - ImageResize # - default
  # - LazyloadImages # - default
  # - ImageAddDimensions

  # - CombineJs # - default
  # - JsOptimize # - default
  # - DeferJs

