application: your-app-id
version: master
runtime: go
api_version: go1

# this includes the tailbone api links and /tailbone.js
includes:
  - tailbone

handlers:
  # this links everything else in your client/app folder to be served
  # Change this to something else if your public folder is not client/app
  - url: (/?.*)/
    static_files: client/app\1/index.html
    upload: client/app(.*)/index.html
  - url: /
    static_dir: client/app

builtins:
  - appstats: on
  - deferred: on
  - admin_redirect: on
  - remote_api: on
  # - datastore_admin: on

inbound_services:
  - warmup
  - channel_presence
